name: Github Pages Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4.0.2
      with:
          github-token: ${{secrets.PAGES_TOKEN}}
          script: |
            github.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
